title: Yahui Liu | NLPer
position: Ph.D. Student
affiliation: Soochow University
email: yahuiliu.nlp@foxmail.com

plugins:
  - jekyll-spaceship
  - jekyll-last-modified-at
  # - jekyll-analytics

keywords: minimal academic
description:
  PhD student [@SUDA-HLT](http://hlt.suda.edu.cn), Soochow University
canonical: https://yahui19960717.github.io/

# semantic_scholar: https://www.semanticscholar.org/author/Houquan-Zhou/50986473
# google_scholar: https://scholar.google.com/citations?user=hJWovmAAAAAJ
# cv_link: ./assets/files/cv.pdf
github_link: https://github.com/yahui19960717
# arxiv_link: https://cv.hqzhou.com/arxiv
affiliation_link: https://www.suda.edu.cn

avatar: ./assets/img/IDphoto.png
# favicon: ./assets/img/favicon.svg
favicon_svg: ./assets/img/favicon-3.min.svg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# jekyll_analytics:
#   GoogleAnalytics:
#     id: UA-284490532-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
